version: '3'
services:
  # Container that executes my scripts
  my-app:
    build:
      context: ./my-app
    container_name: my-app
    command: tail -F anything
  # Spark
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080" # gui
      - "7077:7077" # probably won't expose this
  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
  # Kafka
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181' # probably won't expose this
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092' # do I need to expose this?
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  # HBase
  hbase:
    image: 'harisekhon/hbase'
    container_name: hbase
    ports:
      - '16010:16010' # HBase Master web UI
    environment:
      - HBASE_MASTER=0.0.0.0
      - HBASE_MASTER_PORT=16000
      - HBASE_REGIONSERVER_PORT=16020
      - HBASE_REST_PORT=8080
      - HBASE_ZOOKEEPER_QUORUM=zookeeper:2181